routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//awal
// Route::get('/', 'GuestController@index' )->name('index');
Route::get('/', 'GuestController@index' )->name('guests');
Route::get('/foto/{foto}', 'GuestController@foto' )->name('foto');

Route::get('/guests/checkout', 'GuestController@checkout')->name('checkout');
Route::get('/guests/searchresult', 'GuestController@search')->name('searchresult');

Route::get('/redirect-logbook/{q}', 'Auth\AuthController@login');

Route::get('/guests/create', 'GuestController@store')->name('Store');

Route::get('/oldguests', 'GuestController@oldguests');

// Route::get('/', 'Auth\AuthController@index')->name('login');

Route::get('/guests/cekout', 'GuestController@cekout');
Route::get('/guests/success', 'GuestController@success');
Route::get('/guests/rating', 'GuestController@rating');
Route::get('/guests/chooseuser', 'GuestController@chooseuser')->name('chooseuser');
Route::get('/guests/getGuest', 'GuestController@getGuest')->name('getGuest');
Route::get('/guests/oldGuests', 'GuestController@oldGuests');
Route::get('/guests/guestId', 'GuestController@guestsId');
// Route::patch('/co/{id}', 'GuestController@cekout');
Route::resource('/guests', 'GuestController');
// Route::resource('/guests', 'GuestCheckinController');
//cari tamu
Route::any( '/guests/search', 'GuestController@search')->name('search');
Route::any( '/guests/searchGuest', 'GuestController@searchGuest')->name('searchGuest');
Route::get( '/guests/cekout', 'GuestController@cekout');

Route::get('/getLantai/{id}', 'LokasiController@getLantai');


// Route::get('/guests/logbook', 'GuestController@lokasi');
Route::get('/json-lantai', 'GuestController@lantai')->name('jsonLantai');
Route::get('/json-ruangan', 'GuestController@ruangan')->name('jsonRuang');

//Export
Route::get('/tickets/rfo/{id}', 'App\Http\Controllers\ExportController@rfo')->middleware(['checkRole:Super Admin,User,Customer Care,BOD']);
Route::get('/tickets/rfo_maintenance/{id}', 'App\Http\Controllers\ExportController@rfoMaintenance')->middleware(['checkRole:Super Admin,User,Customer Care,BOD']);
Route::post('/tickets/export', 'ExportController@export');
Route::post('/tickets/exportkeluar', 'ExportController@exportkeluar');
Route::post('/tickets/exportreturn', 'ExportController@exportreturn');
Route::post('/tickets/exportLogAssign', 'App\Http\Controllers\ExportController@exportLogAssign')->middleware(['checkRole:Super Admin,User,Customer Care,BOD']);
Route::post('/tickets_internal/exportLogAssign', 'App\Http\Controllers\ExportController@exportLogAssign')->middleware(['checkRole:Super Admin,User,Customer Care,BOD']);
Route::post('/tickets/export-bulk-Assign', 'App\Http\Controllers\ExportController@exportBulkAssign')->middleware(['checkRole:Super Admin,User,Customer Care,BOD']);
//End export
//admin
// Route::get('/admin', 'AdminController@index')->name('admin');

// Route::get('/login', 'AuthController@login')->name('login');
// Route::get('/loginadmin', 'AuthController@login')->name('loginadmin');
// Route::post('/postlogin', 'AuthController@postlogin')->name('postlogin');
// Route::get('/logoutadmin', 'AuthController@logout')->name('logoutadmin');
// Route::get('/logout', 'AuthController@logout')->name('logout');
// Route::get('/guests/create', 'AdminController@create');
// Route::post('/guests', 'AdminController@store');

// Route::group(['middleware' => 'auth'], function () {
//     Route::get('/admin', 'AdminController@index')->name('admin');
//     Route::get('/guests/{id}/show', 'AdminController@show');
//     Route::get('/guests/{id}/edit', 'AdminController@edit');
//     Route::patch('/guests/{id}', 'AdminController@update');

//     Route::get('/co/{id}/cek', 'AdminController@cek');
//     Route::patch('/co/{id}', 'AdminController@cekout');

//     Route::delete('/guests/{id}', 'AdminController@destroy');
//     Route::get('/exportguest','GuestController@guestexport');

//     Route::get('/search','GuestController@index');
//     Route::get('/guestexport','GuestController@index');
//     Route::get('/cetak','GuestPrint@pdf')->name('l_guest');

//     Route::get('/cetakguest/{search1}/{search2}','GuestController@cetakguest')->name('cetakguest');
//     Route::get('/print_siswa','AdminController@print');

//     Route::get('/penilaian/create', 'PenilaianController@create');
// });

//sisi guest
Route::get('/indexutamaguest', 'TamuController@index');
Route::get('/checkin/create', 'TamuController@create');
Route::post('/checkin', 'TamuController@store');
Route::get('/indexcheckout', 'TamuController@indexcheckout');
Route::get('/checkin/{id}/edit', 'TamuController@edit');
Route::patch('/checkin/{id}', 'TamuController@update');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Awal
// Route::get('/', 'Auth\AuthController@index')->name('login');
Route::get('/login', 'Auth\AuthController@indexlogin')->name('login');

Route::get('/admin', 'Auth\AuthController@sso')->name('login_awal');
Route::post('/login', 'Auth\AuthController@login')->name('logins');
Route::get('/logoutadmin', 'Auth\AuthController@logout')->name('logoutadmin');
Route::get('/logout', 'Auth\AuthController@logout')->name('logout');

Route::group(['middleware' => 'auth', 'ceklevel:Super Admin'], function(){
    Route::get('/admin', 'Auth\AuthController@index')->name('admin');
    Route::get('/audit', 'AuditLogController@index')->name('audit');
    Route::get('/guests/{id}/show', 'AdminController@show');
    Route::get('/guests/{id}/edit', 'AdminController@edit');
    Route::patch('/guests/{id}', 'AdminController@update');

    Route::get('/co/{id}/cek', 'AdminController@cek');
    Route::patch('/co/{id}', 'AdminController@cekout');

    Route::delete('/guests/{id}', 'AdminController@destroy');
    Route::get('/exportguest','GuestController@guestexport');

    Route::get('/search','GuestController@index');
    Route::get('/guestexport','GuestController@index');
    Route::get('/cetak','GuestPrint@pdf')->name('l_guest');

    Route::get('/cetakguest/{search1}/{search2}','GuestController@cetakguest')->name('cetakguest');
    Route::get('/print_siswa','AdminController@print');

    Route::get('/penilaian/create', 'PenilaianController@create');
});

Route::group(['middleware' => 'auth', 'ceklevel:Admin,User'], function(){
    Route::get('/admin', 'Auth\AuthController@index')->name('admin');
    Route::get('/guests/{id}/show', 'AdminController@show');
    Route::get('/guests/{id}/edit', 'AdminController@edit');
    Route::patch('/guests/{id}', 'AdminController@update');

    Route::get('/co/{id}/cek', 'AdminController@cek');
    Route::patch('/co/{id}', 'AdminController@cekout');

    Route::delete('/guests/{id}', 'AdminController@destroy');
    // Route::post('/guests/checkout/process', 'AdminController@destroy')->name('checkout.process');
    
    //Awal
    // Route::post('/guests/checkout/process', 'AdminController@destroy')->name('checkout.process');
    //addimam
    // Route::post('/guests/checkout/process', 'AdminController@cekoutnew')->name('checkout.process');
    

    Route::get('/search','GuestController@index');
    Route::get('/exportguest','GuestController@guestexport');

    Route::get('/search','GuestController@index');
    Route::get('/guestexport','GuestController@index');
    Route::get('/cetak','GuestPrint@pdf')->name('l_guest');

    Route::get('/cetakguest/{search1}/{search2}','GuestController@cetakguest')->name('cetakguest');
    Route::get('/print_siswa','AdminController@print');

    Route::get('/penilaian/create', 'PenilaianController@create');

});
Route::post('/test', 'TestController@test')->name('test');
Route::post('/guests/checkout/process', 'GuestController@cekoutnew')->name('checkout.process');

app/Guest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\facades\DB;
use App\Lokasi;
use App\Ruang;
use App\Lantai;
use Illuminate\Database\Eloquent\SoftDeletes;

class Guest extends Model
{
    use SoftDeletes;
    protected $table = 'guests';
    protected $dates = ['deleted_at'];
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = [
        'datein', 'dateout', 'guestid', 'name', 'telephone','company', 'email', 
        'activity', 'noRack', 'noLoker', 'lokasi_id', 'lantai_id', 'ruangan_id', 'access', 'remarks', 
        'durasi', 'foto', 'service_quality', 'infrastructure_quality','clean_quality', 'visitdatacenterint','id_status'
    ];
    public function lokasi(){
        return $this->belongsTo('App\Lokasi');
    }

}

resources/views/guests/checkout.blade.php
@extends('guests.layout')
@section('after_style')
@endsection
@section('content')
@include('guests.pesan')

<div class="container" style="margin-top: 3%;">
        <form action="{{ route('search')}}" method="POST" role="search">
            {{ csrf_field() }}
            <div class="input-group">
                <input type="text" class="form-control" name="q" required
                    placeholder="Find Guest"> <span class="input-group-btn">
                    <button type="submit" class="btn btn-success" style="margin-left: 10px;">
                        <span class="glyphicon glyphicon-search">Search!</span>
                    </button>
                </span>
            </div>
        </form>
</div>
<style>
    @media screen and (max-width: 620px) {
    .footer{
        padding-bottom: 260px;
    }
}

    @media only screen and (min-width: 1401px) {
    .footer{
        margin-bottom: 270px;
    }
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container" style="margin-top: 3%;">
                <h3 class="text-center" >Please Input your Phone Number</h3>
            </div>
           
            
                {{-- <div class="row" style="margin-top: 3%;">
                                    @if ($guests)
                    @foreach ($guests as $guest)
                    <a href="{{ route('guests.show',$guest->id) }}">
                    <div class="col-md-4" style="margin-bottom: 3%;"> 
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="{{ asset('/storage/photos/' . $guest->foto) }}" alt="Card image cap">
                        <div class="card-body">
                          <h5 class="card-title text-dark">{{ $guest->name }} </h5>
                          <h5 class="card-text text-dark">{{ $guest->datein }} </h5>
                          <label>Date out : </label>
                            <div id="time" style="background-color: #ecf0f1; border: 1px dashed grey; height: auto; margin: 1px 0px; padding: 3px; text-align: left; width: auto;">   
                            </div>  
                          <p class="card-text text-dark">Aktivitas : {{ $guest->activity }}</p>
                          <p class="card-text text-dark">Nomor Rack: {{ $guest->noRack }}</p>
                          <p class="card-text text-dark">Nomor Loker: {{ $guest->noLoker }}</p>
                        <form action="{{ route('guests.destroy',$guest->id) }}" method="POST">
                        <a class="btn btn-primary" href="{{ route('guests.edit',$guest->id) }}">Edit</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Checkout</button>
                      </div>
                    </div>
                    </a>
                    </div>
                @endforeach
                    {!! $guests->links() !!}
                @endif
                </div> --}}
        </div>
    </div>
    <div class="footer">

    </div>
    <br/><br/><br/><br/><br/><br/><br/><br/><br/>
</div>
    <!-- end of container -->
@endsection

@section('script')
@endsection

resources/views/guests/checkoutnew.blade.php
@extends('guests.layoutnew')
@section('after_style')
@endsection
@section('content')
@include('guests.pesan')

<a class="navbar-brand text-white" style="margin-left: auto; margin-right: auto;">
    <img src="{{ asset('images') }}/matrixlogo.png" alt="" width="120" height="50">
</a>
<br>
<br>
<br>
<br>

<div class="container">
        <form action="{{ route('search')}}" method="POST" role="search">
            {{ csrf_field() }}
            <div class="input-group" >
                <input type="text" class="form-control" name="q" required
                    placeholder="Find Guest"> <span class="input-group-btn">
                    <button type="submit" class="btn btn-success" style="margin-left: 10px;">
                        <span class="glyphicon glyphicon-search">Search!</span>
                    </button>
                </span>
            </div>
        </form>
</div>
<style>
    @media screen and (max-width: 620px) {
    .footer{
        padding-bottom: 260px;
    }
}

    @media only screen and (min-width: 1401px) {
    .footer{
        margin-bottom: 270px;
    }
}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="container" style="margin-top: 3%;">
                <h3 class="text-center" >Please Input your Phone Number</h3>
            </div>

        </div>
    </div>
    <div class="footer">

    </div>
    <br/>
</div>
    <!-- end of container -->
@endsection

@section('script')
@endsection

resources/views/guests/chooseUser.blade.php
@extends('guests.layout')
@section('after_style')
@endsection
@section('content')
@include('guests.pesan')
<link href="{{asset('css/choose.css')}}" rel="stylesheet" type="text/css">
{{-- <link href="{{asset('css/rating2.css')}}" rel="stylesheet" type="text/css"> --}}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
    integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
    integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous">
</script>

<html>
  <body>
    <div class="row justify-content-center mt-5">
        <section class="flex" id="finn">
          <div class="col-12">
        <div>
          <figure class="text-center">
            <img src="{{ asset('images') }}/model.png" alt="" width="105" height="100">
            <figcaption>New Customer? <br/> Register Here!</figcaption>
          </figure>
          <button type="button" class="btn btn-light text-center"><a href="{{ route('guests.create') }}">Here!</a></button>
        </div>
      </section>
      <section class="flex" id="jake">
        <div class="col-12">
          <figure class="text-center">
            <img src="{{ asset('images') }}/model.png" alt="" width="105" height="100">
            <figcaption>Returning <br/> Customer</figcaption>
          </figure>

          <button type="button" class="btn btn-light"><a href="{{ route('getGuest')}}">Here!</a></button>
        </div>
      </section>
    </div>
  </body>
</html>

<!-- end of container -->
@endsection

@section('script')
@endsection

resources/views/guests/edit.blade.php
@extends('guests.layout')
@section('content')
    <div class="container" style="margin-bottom: 10%;">
        <div class="row">
            <div class="col-md-12">
                <form method="POST" id="myform" action="{{ route('guests.update',$guest->id) }}">
                {{ csrf_field() }}
                @method('PUT')
                    <fieldset>
                        <legend>Edit {{ $guest['nama'] }}</legend>
                        <div class="row">
                            <div class="col-md-8">
                                @if ($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <div class="form-group">
                                    <label for="nama">Nama</label>
                                    <input class="form-control @if($errors->has('nama')) border border-danger @endif " type="text" id="nama"  name="nama" value=" {{ $guest['nama'] }} "/>
                                </div>
                                <div class="form-group">
                                    <label for="dari">Dari</label>
                                    <input name="dari" class="form-control @if($errors->has('dari')) border border-danger @endif" type="text" id="dari" value=" {{ $guest['dari'] }} "/>
                                </div>
                                <div class="form-group">
                                    <label for="keperluan">Keperluan</label>
                                    <input name="keperluan" class="form-control @if($errors->has('keperluan')) border border-danger @endif" type="text" id="keperluan" value=" {{ $guest['keperluan'] }} "/>
                                </div>
                                <div class="form-group">
                                    <label for="keterangan">Keterangan</label>
                                    <input name="keterangan" class="form-control @if($errors->has('keterangan')) border border-danger @endif" type="text" id="keterangan" value=" {{ $guest['keterangan'] }} "/>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group" style="">
                                    <div id="my_camera" class="rounded"></div>
                                </div>
                                <div class="form-group">
                                    <a href="javascript:void(take_snapshot())" class="btn btn-primary">Ambil foto</a>
                                    <input type="hidden" id="foto"  name="foto" value=" {{ $guest['foto'] }} " >
                                </div>
                                <div class="form-group">
                                    <div id="my_result" ></div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <input type="submit" value="Submit" class="btn btn-primary btn-lg btn-block">
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')
<script src="{{ asset('js') }}/webcam.min.js"></script>
    <script language="JavaScript">
    Webcam.set({
    width: 320,
    height: 240,
    dest_width: 320,
    dest_height: 240,
    image_format: 'png',
    jpeg_quality: 90,
    force_flash: false
});

    Webcam.attach( '#my_camera' );
    
    function take_snapshot() {
        Webcam.snap( function(data_uri, canvas, context) {
            document.getElementById('my_result').innerHTML = '<img src="'+data_uri+'"/>';
            var raw_image_data = data_uri.replace(/^data\:image\/\w+\;base64\,/, '');
            document.getElementById('foto').value = raw_image_data;
            console.log(raw_image_data);
        } );
    }
</script>
@endsection

resources/views/guests/searchresult.blade.php
@extends('guests.layout')
@section('after_style')
@endsection
@section('content')
@include('guests.pesan')
<link href="{{asset('css/ratingkedua.css')}}" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
{{-- <link href="{{asset('css/rating2.css')}}" rel="stylesheet" type="text/css"> --}}
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
    integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous">
</script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
    integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous">
</script>
<link href="{{asset('css/backlight.css')}}" rel="stylesheet" type="text/css">
<div class="container" style="margin-top: 3%;">
        <form action="{{route('search')}}" method="POST" role="search">
            {{ csrf_field() }}
            <div class="input-group">
                <input type="text" class="form-control" name="q"
                    placeholder="Find Guest"> <span class="input-group-btn">
                    <button type="submit" class="btn btn-success"  style="margin-left: 10px;">
                        <span class="glyphicon glyphicon-search">Cari</span>
                    </button>
                </span>
            </div>
        </form>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {{-- <div class="container" style="margin-top: 3%;">
                <h3 class="text-center" >Hasil Pencarian</h3>
            </div> --}}
            <header class='header text-center' style="margin-top: 10px;">
                <h3>How satisfied are you with our service?</h3>
                <p><b>Let us know, to improve our service performance</b></p>
            </header>
            @if ($guests)
            @foreach ($guests as $guest)


            <form action="{{ route('checkout.process') }}" method="post">
                @csrf

                <div hidden id="id">
                    <input value="{{$guest->id}}" name="id" type="text" class="form-control bg-light"
                        id="id">
                    </div>
                <div
                <div class="row justify-content-center" style="text-align: center">

                <section>
                <div class="row">
                        <div class="col-3" id="servicequalitybut">
                        <input class="star star-4" id="star-4" type="radio" name="service_quality" value="4"/>
                        <label class="star star-4" for="star-4"></label>
                        <input class="star star-3" id="star-3" type="radio" name="service_quality" value="3"/>
                        <label class="star star-3" for="star-3"></label>
                        <input class="star star-2" id="star-2" type="radio" name="service_quality" value="2"/>
                        <label class="star star-2" for="star-2"></label>
                        <input class="star star-1" id="star-1" type="radio" name="service_quality" value="1"/>
                        <label class="star star-1" for="star-1"></label><br><br><br>
                        <p class="col-12">Service of Maintaning Customer Data Security</p>
                        </div>
                        <div class="col-3" id="infqualitybut">
                        <input class="star star-4" id="star-42" type="radio" name="infrastructure_quality" value="4"/>
                        <label class="star star-4" for="star-42"></label>
                        <input class="star star-3" id="star-32" type="radio" name="infrastructure_quality" value="3"/>
                        <label class="star star-3" for="star-32"></label>
                        <input class="star star-2" id="star-22" type="radio" name="infrastructure_quality" value="2"/>
                        <label class="star star-2" for="star-22"></label>
                        <input class="star star-1" id="star-12" type="radio" name="infrastructure_quality" value="1"/>
                        <label class="star star-1" for="star-12"></label>
                        <p style="text-align: center">Quality of Infrastructure</p>
                        </div>
                        <div class="col-3" id="cleanqualitybut">
                        <input class="star star-4" id="star-43" type="radio" name="clean_quality" value="4"/>
                        <label class="star star-4" for="star-43"></label>
                        <input class="star star-3" id="star-33" type="radio" name="clean_quality" value="3"/>
                        <label class="star star-3" for="star-33"></label>
                        <input class="star star-2" id="star-23" type="radio" name="clean_quality" value="2"/>
                        <label class="star star-2" for="star-23"></label>
                        <input class="star star-1" id="star-13" type="radio" name="clean_quality" value="1"/>
                        <label class="star star-1" for="star-13"></label>
                        <p style="text-align: center">Service for In and Out Equipment </p>
                        </div>
                        <div class="col-3" id="visitdatacenter">
                        <input class="star star-4" id="star-444" type="radio" name="visitdatacenterint" value="4"/>
                        <label class="star star-4" for="star-444"></label>
                        <input class="star star-3" id="star-333" type="radio" name="visitdatacenterint" value="3"/>
                        <label class="star star-3" for="star-333"></label>
                        <input class="star star-2" id="star-222" type="radio" name="visitdatacenterint" value="2"/>
                        <label class="star star-2" for="star-222"></label>
                        <input class="star star-1" id="star-111" type="radio" name="visitdatacenterint" value="1"/>
                        <label class="star star-1" for="star-111"></label>
                        <p style="text-align: center">Service for Customer Visits to Data Center </p>
                        </div>

                </div>
                </section>
            </div>
        </div>
        <div class="col-md-12">
            <div class="row mt-5 justify-content-center">
                <header class='header text-center' style="margin-top: 10px;">
                    <p><b>Give us critics and suggestions, to improve our service performance</b></p>
                </header>
                <div class="form-group col-md-12">
                    <textarea type="text" class="form-control" placeholder="Leave your comments" name="remarks" name="critics"></textarea>
                </div>
            </div>
        </div>

    </div>
                <div class="row justify-content-center" style="margin-top: 3%;">

                    {{-- <a href="{{ route('guests.show',$guest->id) }}"> --}}
                    <div class="col-md-4" style="margin-bottom: 3%;">
                        <style>
                            @media screen and (max-width: 620px) {
                            .card{
                                margin-left: 82px;
                            }
                          }
                          @media screen and (max-width: 620px) {
                            .button{
                                margin-left: 150px;
                            }
                          }
                          </style>
                    <div class="card" style="width: 18rem;">
                        <?php
                            $foto = '/photos/photos/'.$guest->foto;
                        ?>
                        <img class="card-img-top" src="{{ url($foto) }}" alt="Card image cap">
                        <div class="card-body">
                          <h5 class="card-title text-dark">{{ $guest->name }} </h5>
                          <h5 class="card-text text-dark">{{ $guest->datein }} </h5>
                          <label>Date out : </label>
                            <div id="time" style="background-color: #ecf0f1; border: 1px dashed grey; height: auto; margin: 1px 0px; padding: 3px; text-align: left; width: auto;">
                            </div>
                          <p class="card-text text-dark">Activity : {{ $guest->activity }}</p>
                          <p class="card-text text-dark">Number Rack: {{ $guest->noRack }}</p>
                          <p class="card-text text-dark">Number Loker: {{ $guest->noLoker }}</p>

                          <button id="checkoutbutton" type="submit" class="btn btn-danger">Checkout</button>

                        {{-- <form action="{{ route('guests.destroy',$guest->id) }}" method="POST"> --}}
                        {{-- <a class="btn btn-primary" href="{{ route('guests.edit',$guest->id) }}">Edit</a> --}}
                        {{-- @csrf
                        @method('DELETE')
                        <button id="checkoutbutton" type="submit" class="btn btn-danger">Checkout</button>
                      </div> --}}
                    </div>
                    {{-- </a> --}}
                    </div>
                @endforeach
                    {!! $guests->links() !!}
                @endif
                </div>
        </div>
    </div>
</div>
    <!-- end of container -->
@endsection

@section('script')
<script type="text/javascript">
    $("#star-53").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-43").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-33").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-23").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-13").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-52").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-42").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-32").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-22").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-12").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-5").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-4").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-3").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-2").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-1").change(function () {
        $("#checkoutbutton").attr("disabled", true);
    });
    $("#star-444").change(function () {
        $("#checkoutbutton").attr("disabled", false);
    });
    $("#star-333").change(function () {
        $("#checkoutbutton").attr("disabled", false);
    });
    $("#star-222").change(function () {
        $("#checkoutbutton").attr("disabled", false);
    });
    $("#star-1111").change(function () {
        $("#checkoutbutton").attr("disabled", false);
    });
</script>
@endsection